-- SQL SCHEMA FOR IGREJA CRISTÃ EVANGÉLICA NOVA VIDA
-- Copy and run this script in the SQL Editor of your Supabase Dashboard

-- 1. SERMONS TABLE
CREATE TABLE IF NOT EXISTS public.sermons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title_pt TEXT NOT NULL,
    title_en TEXT,
    series_pt TEXT NOT NULL,
    series_en TEXT,
    preacher_pt TEXT NOT NULL,
    preacher_en TEXT,
    date DATE NOT NULL,
    theme_pt TEXT,
    theme_en TEXT,
    duration TEXT,
    video_url TEXT,
    image TEXT,
    verse TEXT
);

-- 2. EVENTS TABLE
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    day TEXT NOT NULL,
    month_pt TEXT NOT NULL,
    month_en TEXT,
    year TEXT NOT NULL,
    title_pt TEXT NOT NULL,
    title_en TEXT,
    description_pt TEXT,
    description_en TEXT,
    time TEXT NOT NULL,
    location_pt TEXT NOT NULL,
    location_en TEXT,
    category TEXT DEFAULT 'proximos', -- 'proximos' | 'conferencias' | 'ministerios'
    image TEXT
);

-- 3. WEEKLY SCHEDULES / SERVICES TABLE
CREATE TABLE IF NOT EXISTS public.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    day_time_pt TEXT NOT NULL,
    day_time_en TEXT,
    title_pt TEXT NOT NULL,
    title_en TEXT,
    description_pt TEXT,
    description_en TEXT,
    sort_order INT DEFAULT 1
);

-- Enable Row Level Security (RLS) on all tables for maximum safety
ALTER TABLE public.sermons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

-- 4. READ POLICIES (Publicly readable)
CREATE POLICY "Allow public read access on sermons" ON public.sermons FOR SELECT USING (true);
CREATE POLICY "Allow public read access on events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow public read access on schedules" ON public.schedules FOR SELECT USING (true);

-- 5. WRITE/EDIT POLICIES (Only authenticated users can modify the tables)
CREATE POLICY "Allow authenticated insert on sermons" ON public.sermons FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on sermons" ON public.sermons FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on sermons" ON public.sermons FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert on events" ON public.events FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on events" ON public.events FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on events" ON public.events FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert on schedules" ON public.schedules FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on schedules" ON public.schedules FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on schedules" ON public.schedules FOR DELETE USING (auth.role() = 'authenticated');

-- 6. SEED DATA (Optional initial rows to populate the site immediately after creation)
-- Sermons seed
INSERT INTO public.sermons (title_pt, title_en, series_pt, series_en, preacher_pt, preacher_en, date, theme_pt, theme_en, duration, video_url, image, verse)
VALUES 
('A Suficiência das Escrituras', 'The Sufficiency of Scripture', 'Sola Scriptura', 'Sola Scriptura', 'Rev. Marcos S. Oliveira', 'Rev. Marcos S. Oliveira', '2026-07-12', 'Fidelidade Bíblica', 'Biblical Faithfulness', '42 min', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1504052434569-70ad58565b90?auto=format&fit=crop&w=600&q=80', '2 Timóteo 3:16-17'),
('O Amor Que Transforma', 'The Transforming Love', 'Família de Fé', 'Family of Faith', 'Pr. André Silva', 'Pastor André Silva', '2026-07-05', 'Amor Cristão', 'Christian Love', '38 min', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1438029071396-1e831a7fa6d8?auto=format&fit=crop&w=600&q=80', '1 João 4:19');

-- Events seed
INSERT INTO public.events (day, month_pt, month_en, year, title_pt, title_en, description_pt, description_en, time, location_pt, location_en, category, image)
VALUES 
('18', 'AGO', 'AUG', '2026', 'Congresso de Famílias 2026', 'Family Conference 2026', 'Três dias de palestras, aconselhamento e louvor voltados para o fortalecimento do lar.', 'Three days of lectures, counseling, and worship focused on strengthening the home.', '19:30', 'Templo Principal', 'Main Sanctuary', 'conferencias', 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80'),
('05', 'SET', 'SEP', '2026', 'Ação Social no Bairro', 'Neighborhood Social Action', 'Distribuição de cestas, atendimento médico básico e atividades recreativas infantis gratuitas.', 'Distribution of food baskets, basic medical care, and free children''s recreational activities.', '09:00', 'Estacionamento e Entorno', 'Parking Lot & Surroundings', 'proximos', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=600&q=80');

-- Schedules seed
INSERT INTO public.schedules (day_time_pt, day_time_en, title_pt, title_en, description_pt, description_en, sort_order)
VALUES 
('Domingo, 09h30', 'Sunday, 09:30 AM', 'Escola Bíblica Dominical (EBD)', 'Sunday Bible School', 'Classes para crianças, jovens e adultos sobre teologia, casamento e vida cristã.', 'Classes for children, youth, and adults about theology, marriage, and Christian life.', 1),
('Domingo, 18h00', 'Sunday, 06:00 PM', 'Culto de Adoração Principal', 'Main Worship Service', 'Nosso encontro comunitário principal focado na liturgia bíblica, louvor congregacional e pregação bíblica expositiva.', 'Our primary community gathering focused on biblical liturgy, congregational praise, and expository biblical preaching.', 2),
('Terça-feira, 20h00', 'Tuesday, 08:00 PM', 'Reunião de Oração e Estudo Bíblico', 'Prayer and Bible Study Meeting', 'Momento devocional no meio da semana com períodos de oração comunitária e estudo temático aprofundado.', 'Mid-week devotional moment with times of community prayer and deep thematic study.', 3);
